"""Rewrite guess_word field in gamesession, add words table

Revision ID: 158a40bc0e94
Revises: eaed7c829ea9
Create Date: 2024-10-18 21:27:54.477902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "158a40bc0e94"
down_revision: Union[str, None] = "eaed7c829ea9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("word", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("word"),
    )
    op.add_column(
        "game_sessions",
        sa.Column(
            "guess_word_id",
            sa.Integer(),
            nullable=False,
            comment="ID слова для отгадывания",
        ),
    )
    op.alter_column(
        "game_sessions",
        "owner_id",
        existing_type=sa.INTEGER(),
        comment="Владелец сессии",
        existing_nullable=False,
    )
    op.alter_column(
        "game_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Дата создания сессии",
        existing_nullable=False,
    )
    op.alter_column(
        "game_sessions",
        "finished_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Дата окончания сессии",
        existing_nullable=True,
    )
    op.create_foreign_key(
        None,
        "game_sessions",
        "words",
        ["guess_word_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "game_sessions", type_="foreignkey")
    op.alter_column(
        "game_sessions",
        "finished_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Дата окончания сессии",
        existing_nullable=True,
    )
    op.alter_column(
        "game_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Дата создания сессии",
        existing_nullable=False,
    )
    op.alter_column(
        "game_sessions",
        "owner_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Владелец сессии",
        existing_nullable=False,
    )
    op.drop_column("game_sessions", "guess_word_id")
    op.drop_table("words")
    # ### end Alembic commands ###
