"""add_game_state_to_game_sessions

Revision ID: 9ce58efd7a70
Revises: 501f285dfe2a
Create Date: 2024-10-30 21:33:23.265356

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ce58efd7a70"
down_revision: Union[str, None] = "501f285dfe2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_sessions",
        sa.Column(
            "game_state",
            sa.String(),
            nullable=True,
            comment="Состояние игры (WIN, IN_PROGRESS, LOSS)",
            default='IN_PROGRESS',
        ),
    )
    op.execute("UPDATE game_sessions SET game_state = 'LOSS' WHERE game_state IS NULL")
    op.alter_column(
        "game_sessions",
        "game_state",
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_sessions", "game_state")
    # ### end Alembic commands ###
