"""Creating a game session by an unregistered person

Revision ID: db2e5e4b2b81
Revises: 109f37bc1377
Create Date: 2024-12-04 16:49:52.898822

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db2e5e4b2b81"
down_revision: Union[str, None] = "109f37bc1377"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "game_attempts",
        "owner_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="Владелец попытки (ID пользователя)",
    )
    op.alter_column(
        "game_sessions",
        "owner_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="Владелец сессии",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "game_sessions",
        "owner_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="Владелец сессии",
    )
    op.alter_column(
        "game_attempts",
        "owner_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="Владелец попытки (ID пользователя)",
    )
    # ### end Alembic commands ###
