"""Add attempt_word to game_attempt table

Revision ID: 501f285dfe2a
Revises: 737c730857b3
Create Date: 2024-10-27 15:45:01.065463

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "501f285dfe2a"
down_revision: Union[str, None] = "737c730857b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_attempts",
        sa.Column(
            "attempt_word",
            sa.String(),
            nullable=False,
            comment="Слово, введенное пользователем в попытке",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_attempts", "attempt_word")
    # ### end Alembic commands ###
