"""Add game attempt

Revision ID: 737c730857b3
Revises: 158a40bc0e94
Create Date: 2024-10-27 15:41:44.105839

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "737c730857b3"
down_revision: Union[str, None] = "158a40bc0e94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_attempts",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID записи",
        ),
        sa.Column(
            "session_id",
            sa.UUID(),
            nullable=False,
            comment="ID игровой сессии, к которой относится попытка",
        ),
        sa.Column(
            "owner_id",
            sa.Integer(),
            nullable=False,
            comment="Владелец попытки (ID пользователя)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Дата и время создания попытки",
        ),
        sa.Column(
            "attempt_number",
            sa.Integer(),
            nullable=False,
            comment="Номер попытки (от 0 до 5)",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["game_sessions.session_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_attempts")
    # ### end Alembic commands ###
